name: deex_bloc_mobile_app_dev
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: ^3.5.1
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  #sflutter_blue: ^0.8.0
  get: ^4.6.6
  http: ^1.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.4.0
  logger: ^2.4.0
  assets: ^0.0.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  data_table_2: ^2.5.15
  camera: ^0.11.0+2
  linked_scroll_controller: ^0.2.0
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  table_calendar: ^3.1.2
  file_picker: ^8.1.2
  device_info_plus: ^11.3.0
  accordion: ^2.6.0
  easy_stepper: ^0.8.5+1
  syncfusion_flutter_datepicker: ^26.2.14
  fluttertoast: ^8.2.14
  cached_network_image: ^3.3.1
  excel: ^4.0.6
  pdf: ^3.11.1
  geolocator: ^13.0.1
  calendar_date_picker2: ^1.1.7
  google_maps_flutter: ^2.10.1
  location: ^7.0.1
  flutter_easyloading: ^3.0.5
  open_filex: ^4.7.0
  nfc_manager: ^3.5.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^6.1.0
  webview_flutter_android: ^4.1.0
  webview_flutter: ^4.10.0
  image: ^4.3.0
  spreadsheet_decoder: ^2.3.0
  syncfusion_flutter_xlsio: ^26.2.14
  flutter_typeahead: ^5.2.0
  signature: ^5.5.0
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  flutter_local_notifications: ^19.2.1
  timeago: ^3.7.1
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  sqflite_common_ffi_web: ^1.1.1
  bloc: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/src/features/home/assets/img/delex_logo_transparent_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: false

flutter:
  uses-material-design: true
  assets:
    - env.dev
    - lib/src/features/login/assets/svg/work_inspections.svg
    - lib/src/features/login/assets/svg/delex_icon.svg
    - lib/src/features/login/assets/inspections.png
    - lib/src/features/login/assets/login_background.jpeg
    - lib/src/features/login/assets/delex_background_image.png
    - lib/src/features/login/assets/login_new_bg.png
    - lib/src/features/login/assets/svg/visibility_on.svg
    - lib/src/features/login/assets/svg/visibility_off.svg
    - lib/src/features/landing_page/assets/svg/quick_access.svg
    - lib/src/features/landing_page/assets/svg/periodic_inspection.svg
    - lib/src/features/landing_page/assets/svg/repair_works.svg
    - lib/src/features/landing_page/assets/svg/go.svg
    - lib/src/features/landing_page/assets/svg/action_required/initial_inspection.svg
    - lib/src/features/landing_page/assets/svg/action_required/periodic_inspection.svg
    - lib/src/features/landing_page/assets/svg/action_required/repair_works.svg
    - lib/src/features/landing_page/assets/svg/menu_section/dashboard.svg
    - lib/src/features/landing_page/assets/svg/menu_section/functional_areas.svg
    - lib/src/features/landing_page/assets/svg/menu_section/ex_inspection.svg
    - lib/src/features/landing_page/assets/svg/menu_section/ex_register.svg
    - lib/src/features/landing_page/assets/svg/menu_section/asset_locator.svg
    - lib/src/features/landing_page/assets/svg/menu_section/to_device.svg
    - lib/src/features/landing_page/assets/svg/menu_section/to_cloud.svg
    - lib/src/features/landing_page/assets/svg/menu_section/logout.svg
    - lib/src/features/landing_page/assets/svg/search_icon.svg
    - lib/src/features/landing_page/assets/svg/menu_section/equipment_locator.svg
    - lib/src/features/home/assets/img/
    - lib/src/features/home/assets/svg/delex_icon.svg
    - lib/src/features/home/assets/svg/dashboard_icon.svg
    - lib/src/features/home/assets/svg/functional_area_icon.svg
    - lib/src/features/home/assets/svg/ex_register_icon.svg
    - lib/src/features/home/assets/svg/ex_inspection_icon.svg
    - lib/src/features/home/assets/svg/equipment_locator_icon.svg
    - lib/src/features/home/assets/svg/to_device_icon.svg
    - lib/src/features/home/assets/svg/to_server_icon.svg
    - lib/src/features/home/assets/svg/logout_icon.svg
    - lib/src/features/home/assets/svg/settings_icon.svg
    - lib/src/features/home/assets/svg/profile-icon.svg
    - lib/src/features/home/assets/svg/mail-icon.svg
    - lib/src/features/home/assets/svg/Home.jpg
    - lib/src/features/home/assets/svg/delex_logo_menu.svg
    - lib/src/features/home/assets/svg/delex_logo_home_page.svg
    - lib/src/features/home/assets/svg/hamburger_expand.svg
    - lib/src/features/home/assets/svg/hamburger_collapse.svg
    - lib/src/features/functional_areas/assets/svg/add.svg
    - lib/src/features/functional_areas/assets/svg/download.svg
    - lib/src/features/functional_areas/assets/svg/excel_icon.svg
    - lib/src/features/functional_areas/assets/svg/pdf_icon.svg
    - lib/src/features/functional_areas/assets/svg/remove.svg
    - lib/src/features/ex_register/assets/rfid-icon.svg
    - lib/src/features/ex_register/assets/red.svg
    - lib/src/features/ex_register/assets/green.svg
    - lib/src/features/ex_register/assets/After_Filter.svg
    - lib/src/features/ex_register/assets/After_Filter1.svg
    - lib/src/features/ex_register/assets/After_Filter2.svg
    - lib/src/features/ex_register/assets/Before_Filter.svg
    - lib/src/features/ex_register/assets/yellow.svg
    - lib/src/features/ex_register/assets/red_flag.svg
    - lib/src/features/ex_register/assets/green_flag.svg
    - lib/src/features/ex_register/assets/yellow_flag.svg
    - lib/src/features/ex_register/assets/filter_tick.svg
    - lib/src/features/ex_register/assets/filter.svg
    - lib/src/features/ex_inspections/assets/edit_square.svg
    - lib/src/features/ex_inspections/assets/R-Icon1.svg
    - lib/src/features/ex_inspections/assets/add_circle.svg
    - lib/src/features/dashboard/assets/svg/dashboard.svg
    - lib/src/features/dashboard/assets/svg/filter.svg
    - lib/src/features/dashboard/assets/svg/arrow_outline.svg
    - lib/src/features/dashboard/assets/svg/circle_frame.svg
    - lib/src/features/dashboard/assets/svg/completely_repaired.svg
    - lib/src/features/dashboard/assets/svg/inspection.svg
    - lib/src/features/dashboard/assets/svg/partially_repaired.svg
    - lib/src/features/dashboard/assets/svg/pending_repairs.svg
    - lib/src/features/dashboard/assets/svg/uninspection.svg
    - lib/src/features/dashboard/assets/svg/red_flag.svg
    - lib/src/features/dashboard/assets/svg/yellow_flag.svg
    - lib/src/features/dashboard/assets/svg/green_flag.svg
    - lib/src/features/dashboard/assets/svg/card_red_flag.svg
    - lib/src/features/dashboard/assets/svg/card_yellow_flag.svg
    - lib/src/features/dashboard/assets/svg/card_green_flag.svg
    - lib/src/features/dashboard/assets/svg/redToYellowLine.svg
    - lib/src/features/dashboard/assets/svg/redToGreenLine.svg
    - lib/src/features/dashboard/assets/svg/yellowToGreenLine.svg
    - lib/src/features/ex_inspections/assets/stepper_edit.svg
    - lib/src/features/ex_inspections/assets/error_icon.svg
    - lib/src/features/ex_inspections/assets/arrow_left.svg
    - lib/src/features/ex_inspections/assets/toggle_on.svg
    - lib/src/features/ex_inspections/assets/toggle_off.svg
    - lib/src/features/ex_inspections/assets/file_download_icon.svg
    - lib/src/features/equipment_locator/assets/locator_cancel_icon.svg
    - lib/src/features/device_sync/assets/Close.svg
    - lib/src/features/functional_areas/assets/svg/down_arrow.svg
    - lib/src/features/functional_areas/assets/svg/up_arrow.svg
    - lib/src/features/functional_areas/assets/svg/sort_ascending.svg
    - lib/src/features/functional_areas/assets/svg/sort_descending.svg
    - lib/src/features/functional_areas/assets/svg/reset.svg
    - lib/src/features/functional_areas/assets/svg/search.svg
    - lib/src/features/functional_areas/assets/svg/sort.svg
    - lib/src/features/ex_register/assets/refresh.svg
    - lib/src/features/ex_register/assets/calendar.svg
    - lib/src/features/ex_register/assets/external_link.svg
    - lib/src/features/ex_register/assets/table_header_filter.svg
    - lib/src/features/ex_register/assets/danger_circle.svg
    - lib/src/features/ex_register/assets/danger_triangle.svg
    - lib/src/features/ex_register/assets/shield_done.svg
    - lib/src/features/ex_register/assets/itr_delex_logo.png
    - lib/src/features/home/assets/img/delex_logo.png
    - lib/src/features/functional_areas/assets/svg/filter.svg
    - lib/src/features/functional_areas/assets/svg/asc_desc.svg
    - lib/src/features/functional_areas/assets/svg/close.svg
    - lib/src/features/functional_areas/assets/svg/delete.svg
    - lib/src/features/ex_inspections/assets/image_watermark.svg
    - lib/src/features/ex_inspections/assets/checkboxDrop.svg
    - lib/src/features/ex_inspections/assets/empty_checkbox.svg
    - lib/src/features/ex_inspections/assets/check_icon.svg
    - lib/src/features/ex_inspections/assets/cancel_icon.svg
    - lib/src/features/ex_inspections/assets/empty_checkbox.png
    - lib/src/features/ex_inspections/assets/check_icon.png
    - lib/src/features/ex_inspections/assets/cancel_icon.png
    - lib/src/features/ex_register/fonts/Roboto-Regular.ttf
    - lib/src/features/ex_register/fonts/Roboto-Bold.ttf
    - lib/src/features/ex_register/fonts/Inter_28pt-Regular.ttf
    - lib/src/features/ex_register/fonts/Inter_28pt-Regular.ttf
    - lib/src/features/ex_register/assets/Cancel.png
    - lib/src/features/ex_register/assets/check_itr.png
    - lib/src/features/ex_register/assets/checkbox.svg
    - lib/src/features/notification/asset/location.png
    - lib/src/features/notification/asset/location1.png
    - lib/src/features/notification/asset/Locator_Icon.png
    - lib/src/features/notification/asset/delex_logo.png