org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.incremental.js=false
kotlin.incremental.multiplatform=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.skip.metadata.version.check=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
