org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.incremental.js=false
kotlin.incremental.multiplatform=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.skip.metadata.version.check=true
