// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBocqDauquXcYWhwfr4u20P4x0RLYDqWxs',
    appId: '1:1072772990739:web:9d41f40d210c7b0c29bce6',
    messagingSenderId: '1072772990739',
    projectId: 'delex-mobile',
    authDomain: 'delex-mobile.firebaseapp.com',
    storageBucket: 'delex-mobile.firebasestorage.app',
    measurementId: 'G-YYWWZ1C92V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIP4L0MjjVIsv3zY42_av8X8KaJ90eI0A',
    appId: '1:1072772990739:android:911a81b16044cb0529bce6',
    messagingSenderId: '1072772990739',
    projectId: 'delex-mobile',
    storageBucket: 'delex-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgfd4gWFQooeZ-AOnjggU3L3WRTSh01Bg',
    appId: '1:1072772990739:ios:39aded0386d6577d29bce6',
    messagingSenderId: '1072772990739',
    projectId: 'delex-mobile',
    storageBucket: 'delex-mobile.firebasestorage.app',
    iosBundleId: 'com.example.delexFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgfd4gWFQooeZ-AOnjggU3L3WRTSh01Bg',
    appId: '1:1072772990739:ios:39aded0386d6577d29bce6',
    messagingSenderId: '1072772990739',
    projectId: 'delex-mobile',
    storageBucket: 'delex-mobile.firebasestorage.app',
    iosBundleId: 'com.example.delexFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBocqDauquXcYWhwfr4u20P4x0RLYDqWxs',
    appId: '1:1072772990739:web:f306e83cd8ee519829bce6',
    messagingSenderId: '1072772990739',
    projectId: 'delex-mobile',
    authDomain: 'delex-mobile.firebaseapp.com',
    storageBucket: 'delex-mobile.firebasestorage.app',
    measurementId: 'G-53GKC4L20M',
  );
}
